### TALENTOS

### obtener todos los talentos
GET http://localhost:3000/talento

### obtener un talento por su id
GET http://localhost:3000/talento/8

### crear un talento
POST http://localhost:3000/talento
Content-Type: application/json

{
    "name": "Emma Tejedor",
    "email":"emma@hotmail.com",
    "phone": "3132428838",
    "password": "100323",
    "activo": true
}

### actualizar un talento, excepto el email
PATCH http://localhost:3000/talento/8
Content-Type: application/json

{
    "activo": false
}

### obtener todos los talentos por una habilidad
GET http://localhost:3000/talento/oferta?h=bailar



### CLIENTES

### obtener todos los clientes
GET http://localhost:3000/cliente

### obtener un cliente por su id
GET http://localhost:3000/cliente/1

### crear un cliente
POST http://localhost:3000/cliente
Content-Type: application/json

{
    "name": "Rappi",
    "email":"rappi@hotmail.com",
    "phone": "3124567890",
    "password": "345675",
    "address": "Calle 187a No. 8 - 46"
}

### actualizar un cliente, excepto el email
PATCH http://localhost:3000/talento/1
Content-Type: application/json

{
    "phone": "3121234569"
}

### SERVICIO

### obtener todos los servicios
GET http://localhost:3000/servicio

### obtener un servicio por su id
GET http://localhost:3000/servicio/1

### crear un servicio
POST http://localhost:3000/servicio
Content-Type: application/json

{
    "duracionHoras": 5,
    "anticipo": 5000,
    "pagoTotal": 0,
    "diaHora": "2023-09-26 13:05:49",
    "lugarTrabajo": "BOGOTA",
    "terminadoCliente": true,
    "terminadoTalento": true,
    "talentoId": 5,
    "clienteId": 1
}

### actualizar un servicio
PATCH http://localhost:3000/servicio/4
Content-Type: application/json

{
    "pagoTotal": 1000,
    "terminadoCliente": true,
    "terminadoTalento": true,
    "talentoId": "5",
    "clienteId": "1"
}

### HABILIDAD

### obtener todas las habilidades
GET http://localhost:3000/habilidad

### obtener una habilidad por su id
GET http://localhost:3000/habilidad/1

### crear una habilidad
POST http://localhost:3000/habilidad
Content-Type: application/json

{
    "name": "Bailar",
    "talentoId": 8
}

### eliminar una habilidad
DELETE http://localhost:3000/habilidad/4

### CALIFICACION

### obtener todas las calificaciones
GET http://localhost:3000/calificacion

### obtener una calificacion por su id
GET http://localhost:3000/calificacion/1

### crear una calificacion
POST http://localhost:3000/calificacion
Content-Type: application/json

{
    "calificacion": 5,
    "observacion": "Excelente",
    "servicioId": 4
}
