### USUARIOS

### Crear un usuario
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"Liliana Tejedor",
    "email":"liliana@hotmail.com",
    "password": "123456"
}

### Actualizar un usuario, excepto el email
PATCH http://localhost:3000/user/651491192095f44171c25601
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTQ5MTE5MjA5NWY0NDE3MWMyNTYwMSIsImlhdCI6MTY5NjcwNjM5NywiZXhwIjoxNjk2NzA5OTk3fQ.qADxd65kpDRHOzXmzB92hreaLXZpi9hisoiR9N0THNE
Content-Type: application/json

{
    "password": "123456"
}

### Eliminar un usuario
DELETE http://localhost:3000/user/651491192095f44171c25601


### login un usuario
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "password": "789123",
    "email": "angie@hotmail.com"
}

### NOTES

### Crear una nota
POST http://localhost:3000/note
Content-Type: application/json

{
    "title": "Ingredientes para postre de limon",
    "description":"1 taco de galletas Ducales, 1 tarro grande de Crema de Leche, 3 cucharadas soperas de Maizena, 3 pocillos de leche, 1 pocillo de azúcar, 1 yema de huevo, ½ pocillo de Zumo de limón",
    "id": "651491192095f44171c25601"
}

### Obtener todas las notas, de un usuario
GET http://localhost:3000/note
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTQ5MTE5MjA5NWY0NDE3MWMyNTYwMSIsImlhdCI6MTY5NjcwODA5MSwiZXhwIjoxNjk2NzExNjkxfQ.2Ra5kyvh5R8mkSUh0wSL371e5VZsNWcHkzkkmB1NQIA

### Actualizar una nota
PATCH http://localhost:3000/note/6514c982815c3880e573c899
Content-Type: application/json

{
    "title": "Ingredientes para torta 3 leches"
}

### Eliminar una nota
DELETE http://localhost:3000/note/65149afb0e29be2eb4828a9b


